// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upkjxuvwttqwemsoafcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwa2p4dXZ3dHRxd2Vtc29hZmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTE4OTQsImV4cCI6MjA3MDg4Nzg5NH0.5TUcq1_7xR-1Hl-vXVtHcztT1a9riHiB37poCHCGHHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: 'obrador-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});